package checks

import (
	"context"
	"time"
)

// CISFoundationsManualChecks reports the Azure Foundations recommendations the
// benchmark marks Manual and which no automated check answers, so a reader can
// see that the requirement exists and what evidence satisfies it.
//
// Without these a report simply omitted them, which reads as "not applicable"
// rather than "your auditor will ask and nobody has looked".
//
// The wording is ours. CIS's terms require contacting their legal team before
// reproducing portions of recommendations in third-party documentation, so each
// requirement is described rather than quoted - the same reason cis-azure.json
// carries identifiers and assessment types but no titles.
//
// These are written out as literals rather than built from a table. A table
// reads better but hides the control identifier from every static check we
// have: the guards match on Control: "CIS-..." in the source, and a value
// assembled at runtime is invisible to them. The first version of this file
// registered 31 recommendations that the CIS guard could not see.
type CISFoundationsManualChecks struct{}

func NewCISFoundationsManualChecks() *CISFoundationsManualChecks {
	return &CISFoundationsManualChecks{}
}

func (c *CISFoundationsManualChecks) Name() string {
	return "CIS Azure Foundations Manual Controls"
}

func (c *CISFoundationsManualChecks) Run(ctx context.Context) ([]CheckResult, error) {
	return []CheckResult{
		{
			Control:         "CIS-2.1.3",
			Name:            "Databricks Worker Node Traffic Encrypted",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm traffic between Databricks cluster worker nodes is encrypted in transit",
			Remediation:     "Enable encryption between worker nodes on the cluster policy, which requires a supported runtime and node type",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Databricks workspace -> Compute -> Cluster policy -> Screenshot the setting enforcing inter-node encryption",
			ConsoleURL:      "https://portal.azure.com/#browse/Microsoft.Databricks%2Fworkspaces",
			Frameworks:      map[string]string{"CIS-Azure": "2.1.3", "SOC2": "CC6.7"},
		},
		{
			Control:         "CIS-2.1.4",
			Name:            "Databricks Identities Synced from Entra ID",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm Databricks users and groups come from Microsoft Entra ID rather than being created locally in the workspace",
			Remediation:     "Configure SCIM provisioning from Entra ID to the Databricks account, then remove workspace-local accounts",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Databricks account console -> User management -> Screenshot the provisioning source | Entra ID -> Enterprise applications -> Screenshot the provisioning status",
			ConsoleURL:      "https://portal.azure.com/#browse/Microsoft.Databricks%2Fworkspaces",
			Frameworks:      map[string]string{"CIS-Azure": "2.1.4", "SOC2": "CC6.1"},
		},
		{
			Control:         "CIS-2.1.5",
			Name:            "Databricks Unity Catalog Configured",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm Unity Catalog governs data access for the workspace rather than per-workspace access control",
			Remediation:     "Attach the workspace to a Unity Catalog metastore and migrate the data assets onto it",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Databricks account console -> Data -> Screenshot the metastore and the workspaces attached to it",
			ConsoleURL:      "https://portal.azure.com/#browse/Microsoft.Databricks%2Fworkspaces",
			Frameworks:      map[string]string{"CIS-Azure": "2.1.5", "SOC2": "CC6.3"},
		},
		{
			Control:         "CIS-2.1.6",
			Name:            "Databricks Personal Access Tokens Restricted",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm personal access tokens are limited to the users who need them and carry an expiry",
			Remediation:     "Restrict token creation to a group, set a maximum lifetime, and revoke tokens that never expire",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Databricks workspace -> Settings -> Advanced -> Screenshot token permissions and the maximum lifetime",
			ConsoleURL:      "https://portal.azure.com/#browse/Microsoft.Databricks%2Fworkspaces",
			Frameworks:      map[string]string{"CIS-Azure": "2.1.6", "SOC2": "CC6.1"},
		},
		{
			Control:         "CIS-2.1.8",
			Name:            "Databricks Critical Data Encrypted with Customer-Managed Keys",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm critical Databricks data is encrypted with keys you control rather than platform-managed keys",
			Remediation:     "Configure customer-managed keys for the workspace's managed services and workspace storage",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Databricks workspace -> Encryption -> Screenshot the customer-managed key configuration",
			ConsoleURL:      "https://portal.azure.com/#browse/Microsoft.Databricks%2Fworkspaces",
			Frameworks:      map[string]string{"CIS-Azure": "2.1.8", "SOC2": "CC6.1"},
		},
		{
			Control:         "CIS-2.1.12",
			Name:            "Databricks Groups Reviewed Periodically",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm Databricks group membership is reviewed on a schedule and the review is recorded",
			Remediation:     "Establish a periodic review of Databricks groups and keep the record of who reviewed and what changed",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Databricks account console -> User management -> Groups -> Screenshot the membership, with the dated review record",
			ConsoleURL:      "https://portal.azure.com/#browse/Microsoft.Databricks%2Fworkspaces",
			Frameworks:      map[string]string{"CIS-Azure": "2.1.12", "SOC2": "CC6.2"},
		},
		{
			Control:         "CIS-3.1.1",
			Name:            "MFA Required for Privileged VM Access",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm only identities with multifactor authentication can reach privileged virtual machines",
			Remediation:     "Require MFA through a conditional access policy scoped to the administrative accounts that reach those machines",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Entra ID -> Conditional Access -> Screenshot the policy requiring MFA, and its assignment to the VM administrators",
			ConsoleURL:      "https://entra.microsoft.com/",
			Frameworks:      map[string]string{"CIS-Azure": "3.1.1", "SOC2": "CC6.1"},
		},
		{
			Control:         "CIS-5.1.2",
			Name:            "MFA Required to Register or Join Devices",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm registering or joining a device to the tenant requires multifactor authentication",
			Remediation:     "Set the device settings in Entra ID to require MFA for device registration",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Entra ID -> Devices -> Device settings -> Screenshot the MFA requirement for registering or joining",
			ConsoleURL:      "https://entra.microsoft.com/",
			Frameworks:      map[string]string{"CIS-Azure": "5.1.2", "SOC2": "CC6.1"},
		},
		{
			Control:         "CIS-5.1.4",
			Name:            "Remembered MFA on Trusted Devices Disabled",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm users cannot suppress multifactor prompts by marking a device trusted",
			Remediation:     "Turn off the option allowing users to remember multifactor authentication on trusted devices",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Entra ID -> Security -> MFA -> Screenshot the 'remember MFA' setting showing it disabled",
			ConsoleURL:      "https://entra.microsoft.com/",
			Frameworks:      map[string]string{"CIS-Azure": "5.1.4", "SOC2": "CC6.1"},
		},
		{
			Control:         "CIS-5.3.5",
			Name:            "Disabled Accounts Hold No Permissions",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm accounts that have been disabled no longer carry read, write or owner permissions on subscriptions",
			Remediation:     "Remove role assignments from disabled accounts as part of the leaver process rather than leaving them in place",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Subscription -> Access control (IAM) -> Role assignments -> Screenshot showing no assignment held by a disabled account",
			ConsoleURL:      "https://portal.azure.com/#blade/Microsoft_Azure_Billing/SubscriptionsBlade",
			Frameworks:      map[string]string{"CIS-Azure": "5.3.5", "SOC2": "CC6.2"},
		},
		{
			Control:         "CIS-5.3.6",
			Name:            "Tenant Creator Assignments Reviewed",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm the ability to create new tenants is held by as few identities as possible and is reviewed",
			Remediation:     "Review who holds the tenant creator role, remove the unnecessary and record the review",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Entra ID -> Roles and administrators -> Screenshot the tenant creator assignments with the dated review record",
			ConsoleURL:      "https://entra.microsoft.com/",
			Frameworks:      map[string]string{"CIS-Azure": "5.3.6", "SOC2": "CC6.3"},
		},
		{
			Control:         "CIS-5.5",
			Name:            "Custom Role for Administering Resource Locks",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm resource lock administration is granted through a narrow custom role rather than a broad built-in one",
			Remediation:     "Create a custom role granting only the lock operations and assign it to the people who manage locks",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Subscription -> Access control (IAM) -> Roles -> Screenshot the custom role definition and its assignments",
			ConsoleURL:      "https://portal.azure.com/#blade/Microsoft_Azure_Billing/SubscriptionsBlade",
			Frameworks:      map[string]string{"CIS-Azure": "5.5", "SOC2": "CC6.3"},
		},
		{
			Control:         "CIS-5.6",
			Name:            "Subscription Tenant Transfers Restricted",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm subscriptions cannot be moved into or out of the tenant without authorisation",
			Remediation:     "Set the subscription policy to block transfers, allowing exemptions only where a business case exists",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Subscriptions -> Manage policies -> Screenshot both transfer settings and any recorded exemptions",
			ConsoleURL:      "https://portal.azure.com/#blade/Microsoft_Azure_Billing/SubscriptionsBlade",
			Frameworks:      map[string]string{"CIS-Azure": "5.6", "SOC2": "CC6.3"},
		},
		{
			Control:         "CIS-6.1.1.3",
			Name:            "Activity Log Storage Encrypted with Customer-Managed Keys",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm the storage account holding exported activity logs is encrypted with a key you control",
			Remediation:     "Configure customer-managed key encryption on that storage account and keep the key in a vault with purge protection",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Storage account -> Encryption -> Screenshot the customer-managed key, and the Key Vault holding it",
			ConsoleURL:      "https://portal.azure.com/#browse/Microsoft.Storage%2FStorageAccounts",
			Frameworks:      map[string]string{"CIS-Azure": "6.1.1.3", "SOC2": "CC6.1"},
		},
		{
			Control:         "CIS-6.1.1.5",
			Name:            "NSG Flow Logs Sent to Log Analytics",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm network security group flow logs are captured and delivered into a Log Analytics workspace",
			Remediation:     "Enable flow logs with traffic analytics pointed at a Log Analytics workspace",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Network Watcher -> NSG flow logs -> Screenshot the configuration showing traffic analytics and the target workspace",
			ConsoleURL:      "https://portal.azure.com/#blade/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade",
			Frameworks:      map[string]string{"CIS-Azure": "6.1.1.5", "SOC2": "CC7.2"},
		},
		{
			Control:         "CIS-6.1.1.6",
			Name:            "Virtual Network Flow Logs Sent to Log Analytics",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm virtual network flow logs are captured and delivered into a Log Analytics workspace",
			Remediation:     "Enable VNet flow logs with traffic analytics pointed at a Log Analytics workspace",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Network Watcher -> VNet flow logs -> Screenshot the configuration and the target workspace",
			ConsoleURL:      "https://portal.azure.com/#blade/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade",
			Frameworks:      map[string]string{"CIS-Azure": "6.1.1.6", "SOC2": "CC7.2"},
		},
		{
			Control:         "CIS-6.1.1.7",
			Name:            "Microsoft Graph Activity Sent to a Diagnostic Destination",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm a diagnostic setting exports Microsoft Graph activity logs off the platform",
			Remediation:     "Add a diagnostic setting for Graph activity logs targeting a Log Analytics workspace or storage account",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Entra ID -> Diagnostic settings -> Screenshot the setting covering Graph activity and its destination",
			ConsoleURL:      "https://entra.microsoft.com/",
			Frameworks:      map[string]string{"CIS-Azure": "6.1.1.7", "SOC2": "CC7.2"},
		},
		{
			Control:         "CIS-6.1.1.8",
			Name:            "Entra Activity Sent to a Diagnostic Destination",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm a diagnostic setting exports Entra ID audit and sign-in logs off the platform",
			Remediation:     "Add a diagnostic setting covering the audit and sign-in categories with a retained destination",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Entra ID -> Diagnostic settings -> Screenshot the categories selected and the destination",
			ConsoleURL:      "https://entra.microsoft.com/",
			Frameworks:      map[string]string{"CIS-Azure": "6.1.1.8", "SOC2": "CC7.2"},
		},
		{
			Control:         "CIS-6.1.1.9",
			Name:            "Intune Logs Sent to Log Analytics",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm Intune diagnostic logs are delivered into a Log Analytics workspace",
			Remediation:     "Add a diagnostic setting in Intune targeting the workspace, covering audit and operational logs",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Intune admin center -> Reports -> Diagnostic settings -> Screenshot the setting and its destination",
			ConsoleURL:      "https://portal.azure.com/#blade/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade",
			Frameworks:      map[string]string{"CIS-Azure": "6.1.1.9", "SOC2": "CC7.2"},
		},
		{
			Control:         "CIS-6.1.4",
			Name:            "Resource Logging Enabled Across Supporting Services",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm every service that supports Azure Monitor resource logging has it switched on, not just the ones already checked",
			Remediation:     "Apply an Azure Policy initiative that enables diagnostic settings across supported resource types",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Policy -> Assignments -> Screenshot the diagnostic-settings initiative and its compliance state",
			ConsoleURL:      "https://portal.azure.com/#blade/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade",
			Frameworks:      map[string]string{"CIS-Azure": "6.1.4", "SOC2": "CC7.2"},
		},
		{
			Control:         "CIS-6.1.5",
			Name:            "Production Artifacts Not on Basic, Free or Consumption SKUs",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm production resources needing an availability or support guarantee are not running on Basic, Free or Consumption tiers",
			Remediation:     "Move production workloads onto a SKU carrying the service level the business needs",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Resource -> Scale up / Pricing tier -> Screenshot the tier for each production resource in scope",
			ConsoleURL:      "https://portal.azure.com/#blade/Microsoft_Azure_Billing/SubscriptionsBlade",
			Frameworks:      map[string]string{"CIS-Azure": "6.1.5", "SOC2": "A1.2"},
		},
		{
			Control:         "CIS-6.2",
			Name:            "Resource Locks on Mission-Critical Resources",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm mission-critical resources carry a delete or read-only lock so they cannot be removed by accident",
			Remediation:     "Apply locks to the resources whose loss would interrupt the business, and record which ones are in scope",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Resource -> Locks -> Screenshot the lock on each mission-critical resource",
			ConsoleURL:      "https://portal.azure.com/#blade/Microsoft_Azure_Billing/SubscriptionsBlade",
			Frameworks:      map[string]string{"CIS-Azure": "6.2", "SOC2": "A1.2"},
		},
		{
			Control:         "CIS-7.16",
			Name:            "Network Security Perimeter Around PaaS Services",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm platform-as-a-service resources sit inside a network security perimeter rather than being reachable from anywhere",
			Remediation:     "Create a network security perimeter and associate the PaaS resources that should only be reached from inside it",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Network security perimeter -> Screenshot the perimeter, its associated resources and the access rules",
			ConsoleURL:      "https://portal.azure.com/#browse/Microsoft.Network%2FnetworkSecurityPerimeters",
			Frameworks:      map[string]string{"CIS-Azure": "7.16", "SOC2": "CC6.6"},
		},
		{
			Control:         "CIS-8.1.3.4",
			Name:            "Agentless Scanning for Machines Enabled",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm Defender for Servers has agentless machine scanning switched on",
			Remediation:     "Enable the agentless scanning component in the Defender for Servers plan settings",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Defender for Cloud -> Environment settings -> Defender plans -> Servers -> Screenshot agentless scanning set to On",
			ConsoleURL:      "https://portal.azure.com/#blade/Microsoft_Azure_Security/SecurityMenuBlade",
			Frameworks:      map[string]string{"CIS-Azure": "8.1.3.4", "SOC2": "CC7.1"},
		},
		{
			Control:         "CIS-8.1.3.5",
			Name:            "File Integrity Monitoring Enabled",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm file integrity monitoring is switched on in the Defender for Servers plan",
			Remediation:     "Enable the file integrity monitoring component and point it at a Log Analytics workspace",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Defender for Cloud -> Environment settings -> Defender plans -> Servers -> Screenshot file integrity monitoring set to On",
			ConsoleURL:      "https://portal.azure.com/#blade/Microsoft_Azure_Security/SecurityMenuBlade",
			Frameworks:      map[string]string{"CIS-Azure": "8.1.3.5", "SOC2": "CC7.1"},
		},
		{
			Control:         "CIS-8.1.11",
			Name:            "Cloud Security Benchmark Policies Not Disabled",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm the Microsoft Cloud Security Benchmark policies that are still current have not been set to disabled",
			Remediation:     "Re-enable any non-deprecated policy that has been turned off, or record why the exemption is justified",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Defender for Cloud -> Environment settings -> Security policy -> Screenshot the initiative showing no disabled non-deprecated policies",
			ConsoleURL:      "https://portal.azure.com/#blade/Microsoft_Azure_Security/SecurityMenuBlade",
			Frameworks:      map[string]string{"CIS-Azure": "8.1.11", "SOC2": "CC7.1"},
		},
		{
			Control:         "CIS-8.1.16",
			Name:            "External Attack Surface Monitoring Enabled",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm Defender External Attack Surface Management is enabled so internet-facing exposure is discovered",
			Remediation:     "Enable Defender EASM and add the organisation's seeds so discovery covers the estate",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Defender EASM -> Screenshot the workspace and its discovery groups",
			ConsoleURL:      "https://portal.azure.com/#blade/Microsoft_Azure_Security/SecurityMenuBlade",
			Frameworks:      map[string]string{"CIS-Azure": "8.1.16", "SOC2": "CC7.1"},
		},
		{
			Control:         "CIS-8.2.1",
			Name:            "Defender for IoT Hub Enabled",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm Defender for IoT is enabled on the IoT hubs in the subscription",
			Remediation:     "Turn on Defender for IoT for each hub, or record that no IoT hub is in scope",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "IoT Hub -> Defender for IoT -> Screenshot the plan showing it enabled, or the empty hub list",
			ConsoleURL:      "https://portal.azure.com/#blade/Microsoft_Azure_Security/SecurityMenuBlade",
			Frameworks:      map[string]string{"CIS-Azure": "8.2.1", "SOC2": "CC7.1"},
		},
		{
			Control:         "CIS-8.3.10",
			Name:            "Managed HSM Used Where Required",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm keys with a hardware protection requirement are held in Key Vault Managed HSM rather than a standard vault",
			Remediation:     "Move those keys into a Managed HSM pool and record which keys the requirement applies to",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Key Vault -> Managed HSM -> Screenshot the pool and the keys held in it",
			ConsoleURL:      "https://portal.azure.com/#browse/Microsoft.KeyVault%2FmanagedHSMs",
			Frameworks:      map[string]string{"CIS-Azure": "8.3.10", "SOC2": "CC6.1"},
		},
		{
			Control:         "CIS-9.3.9",
			Name:            "Delete Locks on Storage Accounts",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm storage accounts carry a delete lock so they cannot be removed by accident",
			Remediation:     "Apply a CanNotDelete lock to each storage account holding data the business needs",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Storage account -> Locks -> Screenshot the delete lock",
			ConsoleURL:      "https://portal.azure.com/#browse/Microsoft.Storage%2FStorageAccounts",
			Frameworks:      map[string]string{"CIS-Azure": "9.3.9", "SOC2": "A1.2"},
		},
		{
			Control:         "CIS-9.3.10",
			Name:            "ReadOnly Locks Considered for Storage Accounts",
			Status:          "MANUAL",
			Evidence:        "MANUAL CHECK: Confirm a read-only lock has been considered for storage accounts whose configuration should not change, and the decision recorded",
			Remediation:     "Apply a ReadOnly lock where the configuration is settled, or record why one would break normal operation",
			Priority:        PriorityMedium,
			Timestamp:       time.Now(),
			ScreenshotGuide: "Storage account -> Locks -> Screenshot the lock, or the recorded decision not to apply one",
			ConsoleURL:      "https://portal.azure.com/#browse/Microsoft.Storage%2FStorageAccounts",
			Frameworks:      map[string]string{"CIS-Azure": "9.3.10", "SOC2": "A1.2"},
		},
	}, nil
}
