package checks

import (
	"context"
	"strings"
	"testing"

	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/monitor/armmonitor"
)

func strp(s string) *string { return &s }

func boolp(b bool) *bool { return &b }

// leaf and anyOf conditions never carry each other's fields, per the API, and
// the collector has to read both shapes. A rule expressed with anyOf used to be
// the common one the portal produces.
func TestRecordReadsBothConditionShapes(t *testing.T) {
	c := &CISActivityAlertChecks{subscriptionID: "sub-1"}
	res := armmonitor.ActivityLogAlertResource{
		Name: strp("everything"),
		Properties: &armmonitor.AlertRuleProperties{
			Enabled: boolp(true),
			Scopes:  []*string{strp("/subscriptions/sub-1")},
			Actions: &armmonitor.ActionList{ActionGroups: []*armmonitor.ActionGroupAutoGenerated{{}}},
			Condition: &armmonitor.AlertRuleAllOfCondition{AllOf: []*armmonitor.AlertRuleAnyOfOrLeafCondition{
				{Field: strp("category"), Equals: strp("Administrative")},
				{AnyOf: []*armmonitor.AlertRuleLeafCondition{
					{Field: strp("operationName"), Equals: strp("Microsoft.Network/networkSecurityGroups/write")},
					{Field: strp("operationName"), Equals: strp("Microsoft.Network/networkSecurityGroups/delete")},
				}},
			}},
		},
	}
	rule := c.reduce(&res)
	if !rule.matches("operationName", "Microsoft.Network/networkSecurityGroups/write") {
		t.Error("leaf inside anyOf was not recorded")
	}
	if !rule.matches("operationName", "Microsoft.Network/networkSecurityGroups/DELETE") {
		t.Error("operation matching must be case-insensitive; Azure returns mixed case")
	}
	if !rule.matches("category", "administrative") {
		t.Error("top-level leaf condition was not recorded")
	}
	if rule.matches("operationName", "Microsoft.Sql/servers/firewallRules/write") {
		t.Error("matched an operation the rule does not condition on")
	}
	if f := rule.faults(); len(f) != 0 {
		t.Errorf("a complete rule reported faults: %v", f)
	}
}

func TestFaultsNameEveryReasonARuleDoesNotQualify(t *testing.T) {
	c := &CISActivityAlertChecks{subscriptionID: "sub-1"}
	cases := []struct {
		name string
		res  armmonitor.ActivityLogAlertResource
		want string
	}{
		{
			name: "disabled",
			res: armmonitor.ActivityLogAlertResource{Name: strp("r"), Properties: &armmonitor.AlertRuleProperties{
				Enabled: boolp(false),
				Scopes:  []*string{strp("/subscriptions/sub-1")},
				Actions: &armmonitor.ActionList{ActionGroups: []*armmonitor.ActionGroupAutoGenerated{{}}},
			}},
			want: "it is disabled",
		},
		{
			name: "resource group scope",
			res: armmonitor.ActivityLogAlertResource{Name: strp("r"), Properties: &armmonitor.AlertRuleProperties{
				Enabled: boolp(true),
				Scopes:  []*string{strp("/subscriptions/sub-1/resourceGroups/rg-1")},
				Actions: &armmonitor.ActionList{ActionGroups: []*armmonitor.ActionGroupAutoGenerated{{}}},
			}},
			want: "narrower than the subscription",
		},
		{
			name: "no action group",
			res: armmonitor.ActivityLogAlertResource{Name: strp("r"), Properties: &armmonitor.AlertRuleProperties{
				Enabled: boolp(true),
				Scopes:  []*string{strp("/subscriptions/sub-1")},
			}},
			want: "no action group",
		},
		{
			// CIS is explicit that these rules must not filter on Level,
			// Status or Caller: such a rule fires on a subset of the events.
			name: "narrowed by level",
			res: armmonitor.ActivityLogAlertResource{Name: strp("r"), Properties: &armmonitor.AlertRuleProperties{
				Enabled: boolp(true),
				Scopes:  []*string{strp("/subscriptions/sub-1")},
				Actions: &armmonitor.ActionList{ActionGroups: []*armmonitor.ActionGroupAutoGenerated{{}}},
				Condition: &armmonitor.AlertRuleAllOfCondition{AllOf: []*armmonitor.AlertRuleAnyOfOrLeafCondition{
					{Field: strp("level"), Equals: strp("Critical")},
				}},
			}},
			want: "also filters on level",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := strings.Join(c.reduce(&tc.res).faults(), "; ")
			if !strings.Contains(got, tc.want) {
				t.Errorf("faults() = %q, want it to mention %q", got, tc.want)
			}
		})
	}
}

// An alert rule with no explicit Enabled field is enabled; treating the nil as
// false would fail every rule the API returns without it.
func TestMissingEnabledFieldMeansEnabled(t *testing.T) {
	c := &CISActivityAlertChecks{subscriptionID: "sub-1"}
	rule := c.reduce(&armmonitor.ActivityLogAlertResource{
		Name:       strp("r"),
		Properties: &armmonitor.AlertRuleProperties{Scopes: []*string{strp("/subscriptions/sub-1")}, Actions: &armmonitor.ActionList{ActionGroups: []*armmonitor.ActionGroupAutoGenerated{{}}}},
	})
	if !rule.enabled {
		t.Error("a rule with no Enabled field was treated as disabled")
	}
}

// The scope comparison has to tolerate the trailing slash the API sometimes
// returns, or a subscription-wide rule reads as resource-group scoped.
func TestSubscriptionScopeToleratesTrailingSlash(t *testing.T) {
	c := &CISActivityAlertChecks{subscriptionID: "sub-1"}
	rule := c.reduce(&armmonitor.ActivityLogAlertResource{
		Name:       strp("r"),
		Properties: &armmonitor.AlertRuleProperties{Scopes: []*string{strp("/subscriptions/sub-1/")}},
	})
	if !rule.subScoped {
		t.Error("a subscription scope with a trailing slash was not recognised")
	}
}

// A check that cannot reach the API reports ERROR. A PASS here would be a
// verdict from data nobody read, and an unreachable API is not compliance.
func TestUnreachableClientIsErrorNotPassOrFail(t *testing.T) {
	c := NewCISActivityAlertChecks(nil, nil, "sub-1")
	results, err := c.Run(context.Background())
	if err != nil {
		t.Fatalf("Run returned an error: %v", err)
	}
	if len(results) != 12 {
		t.Fatalf("got %d results, want 12 - every recommendation in 6.1.2 and 6.1.3 must be reported", len(results))
	}
	for _, r := range results {
		if r.Status != StatusError {
			t.Errorf("%s reported %s with no client; want ERROR", r.Control, r.Status)
		}
		if r.Frameworks["CIS-Azure"] == "" {
			t.Errorf("%s carries no CIS-Azure tag, so the framework filter would drop it", r.Control)
		}
	}
}

// Every recommendation the benchmark lists in these sections must appear
// exactly once. The first version of the manual file silently registered
// duplicates, which double-counts a control.
func TestEveryRecommendationInTheSectionIsReportedOnce(t *testing.T) {
	results, err := NewCISActivityAlertChecks(nil, nil, "sub-1").Run(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	want := []string{
		"CIS-6.1.2.1", "CIS-6.1.2.2", "CIS-6.1.2.3", "CIS-6.1.2.4", "CIS-6.1.2.5", "CIS-6.1.2.6",
		"CIS-6.1.2.7", "CIS-6.1.2.8", "CIS-6.1.2.9", "CIS-6.1.2.10", "CIS-6.1.2.11", "CIS-6.1.3.1",
	}
	seen := map[string]int{}
	for _, r := range results {
		seen[r.Control]++
	}
	for _, w := range want {
		if seen[w] != 1 {
			t.Errorf("%s reported %d time(s), want exactly 1", w, seen[w])
		}
	}
	for got := range seen {
		found := false
		for _, w := range want {
			if got == w {
				found = true
			}
		}
		if !found {
			t.Errorf("unexpected control %s", got)
		}
	}
}
